services:
  backend:
    build:
      context: ./api
      dockerfile: 'dev.Dockerfile'
    depends_on:
      - mongo
    environment:
      APP_DEBUG: 'false'
      CERTIF_GEN_FRONTEND: "http://localhost:5173/"
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    networks:
      - certif-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - certif-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      CERTIF_GEN_BACKEND: "http://localhost:3000/"
    ports:
      - '80:80'
    networks:
      - certif-network

volumes:
  mongo-data:

networks:
  certif-network:
