services:
  backend:
    build: ./api
    depends_on:
      - mongo
    environment:
      APP_DEBUG: 'false'
      MONGODB_URI: 'mongodb://mongo:27017/certificate-generator'
    env_file:
      - api/.env
    ports:
      - '3000:3000'
    volumes:
      - ./api:/usr/src/app
    networks:
      - certif-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/usr/src/app/volumes
    networks:
      - certif-network

volumes:
  mongo-data:

networks:
  certif-network:

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - certif-network
