services:
  backend:
    build:
      context: ./api
      dockerfile: 'dev.Dockerfile'
    depends_on:
      - mongo
    environment:
      APP_DEBUG: 'false'
    env_file:
      - ./api/.env
    ports:
      - '3000:3000'
    volumes:
      - ./api:/app
    networks:
      - certif-network

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - certif-network

volumes:
  mongo-data:

networks:
  certif-network:

  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - certif-network
