# use Go for base image
FROM golang:1.22

# set working directory in container
WORKDIR /usr/src/app

# copy all code file to container
COPY . .

# disable cgo
ENV CGO_ENABLED=0

# build app
RUN go build -o app ./

# app entrypoint
ENTRYPOINT ["./app"]

# export port
EXPOSE 3000